Feature/cloudproof rust (#22)
* feat!: move interfaces to CloudproofRust

feat: use with CloudproofRust

fix: benches

feat!: remove interfaces

feat: clean root directory

fix: rebase

feat!: use Kmac256 instead of Kmac128

feat: remove `sha3` dependency

fix:! use CryptoCore v7.0

fix: bump version and fill changelog

ci: remove build.yml

fix: review comments

fix: export Kmac used in `kmac!()` macro

feat: improve `ChainTable` encryption/decryption processes

feat: use Cargo workspace

wip: feat: integrate callback error into Findex error type

feat: use Callback error as Findex error member

feat: rename `Error::CallBack` into `Error::Callback`

fix: CI

Remove unused `actix` dependency in `findex_in_memory`

* refactor: remove sqlite example

* feat: add benches on in memory version

* fix: create feature for 'in memory' version

* feat: print table sizes in benches

* fix: compilation error when bench without `in_memory` feature

* fix: `BLOCK_LENGTH`

Allows 32-bytes UIDs to fit in one block.

---------

Co-authored-by: Manuthor <manu.coste@gmail.com>